### PR TITLE
Add support for cloudfront, includes a unit test

### PR DESCRIPTION
**Pull request by DeviaVir**
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-device

This PR adds compatibility with CloudFront device headers, which can be enabled for any CloudFront to Source proxy.

Effectively I've added a function that tries to extract relevant CloudFront headers and when the user agent matches `Amazon CloudFront`, uses those for further device identification. Since they don't define _which_ devices they detect, but only the type, this feature only works with `isMobile` and `isTablet` functions.

The added unit test checks if the correct response is returned when feeding different cloudfront headers.

### CODE REVIEW

**Comment by serbanghita** [comment]
:beers: 

Can you provide me with a specific business use case?

**Comment by DeviaVir** [comment]
@serbanghita Basically every website on AWS behind a CloudFront instance who have the following CloudFront headers enabled:

screen shot 2015-06-18 at 11 50 36

Basically that means people can use the same (MobileDetect) code for detecting Mobile/Tablet/Desktop on production (behind a CloudFront) or on staging (directly on ELB without those headers).

**Comment by serbanghita** [comment]
@DeviaVir interesting. So Amazon does the detection on their end and inject one these headers?

Thanks a lot for the details!

**Comment by DeviaVir** [comment]
@serbanghita You got it! But only on CloudFront, and only if you whitelist their headers. If you'd go directly to the ELB MobileDetect would just work the way it does.
It's quite handy to have one library (MobileDetect) and two lines of code supporting both, so thanks a thousand for merging this PR.

**Comment by DeviaVir** [comment]
@serbanghita I was looking for an example using the code from my fork, and found it:
https://www.nissan-powerthetrophyride.com/

Mobile stays, Desktop gets redirected to Facebook.

This is the only code used (and of course we whitelisted the CloudFront headers):
```
$mobileDetect = new Mobile_Detect();
$tablet = $mobileDetect->isTablet();
$mobile = $mobileDetect->isMobile();
```
Which works on both staging and production 😎

**Comment by serbanghita** [comment]
Interesting, thanks for all the details and explanations! :beers:

**Pull request merged**
