### PR TITLE
Add a utility function to detect a phone

### PR DESCRIPTION
**Pull request by barchard**
Add a utility function to detect ONLY phones and exclude tablets.

### CODE REVIEW

**Comment by ivankaban** [comment]
work is this case
if ($detect->isMobile() && !$detect->isTablet()){
//
}

**Comment by ChefGaby** [comment]
Serban, I think you should just add a isPhone() function.
I see a lot of people are asking this same questions.

**Comment by serbanghita** [comment]
@ChefGaby I am aware of this request, but haven't decided yet. This is because I might mislead people that we actually know **all** the tablets. While `isMobile` covers 99.99% and `isTablet` about 80% of the tablets out there.

**Comment by Kenshino** [comment]
I don't think this is something you need to worry about. People are contributing new UserAgents all the time and in any case, new devices come out all the time.

There is never going to be a time where you can claim you know all of the tablets or phones or anything like that.

Cheers!

**Pull request closed without merging**
