### PR TITLE
Fixed PHP 7.4: Trying to access array offset on value of type null

### LINKED ISSUE #829: PHP 7.4: Trying to access array offset on value of type null
At first, hi and thank you for this library!

**Issue description**
We recently updated php to 7.4 and we are encountering this notices:
```
PHP Notice: Trying to access array offset on value of type null in vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php:1056
```

UA: 
```
Mozilla/5.0 (Linux; U; Android 4.1.1; cs-cz; HUAWEI G510-0200 Build/HuaweiG510-0200) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

**Suggestions**
Wrap with isset/other existence detection

### PR DESCRIPTION
**Pull request by JanMikes**
Fixes #829

### CODE REVIEW

**Comment by JanMikes** [comment]
I checked the failing job but i do not know what is wrong, i think it is not related to my changes: https://travis-ci.org/github/serbanghita/Mobile-Detect/jobs/664801215?utm_medium=notification&utm_source=github_status

**Comment by fmonts** [comment]
Yeah the test is running on PHP 5.4, the .travis.yml should be updated to support 7.4 (and 7.3), but it's not related to this issue

**Comment by taroff** [comment]
Hi! Have the same issue in my project. I think best fix is just "if (null !== $matchType)" instead of this line. Bc $matchType can be only null or array('matches' => ...) for now.

In your fix we have 2 checks. But second (is_array($matchType['matches']) have no sense bc if (isset($matchType['matches'])) then it's array.

**Comment by serbanghita** [comment]
Thank you, I reproduced this:

```php
$detect = new Mobile_Detect;
//$detect->setUserAgent('Mozilla/5.0 (Linux; U; Android 4.1.1; cs-cz; HUAWEI G510-0200 Build/HuaweiG510-0200) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30');
$detect->setHttpHeaders(array(
    'HTTP_X_WAP_PROFILE' => '',
    'HTTP_USER_AGENT'       => 'Mozilla/5.0 (Linux; U; Android 4.1.1; cs-cz; HUAWEI G510-0200 Build/HuaweiG510-0200) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30',
));
```


```
$ php74 -f examples/test.php
PHP Notice:  Trying to access array offset on value of type null in D:\webserver\www\git\Mobile-Detect\Mobile_Detect.php on line 1056

Notice: Trying to access array offset on value of type null in D:\webserver\www\git\Mobile-Detect\Mobile_Detect.php on line 1056
```

**Pull request merged**
