### PR TITLE
Add src/MobileDetectInterface.php

### PR DESCRIPTION
**Pull request by tattali**

### CODE REVIEW

**Comment by serbanghita** [comment]
@tattali why is this needed?

**Comment by pquerner** [comment]
I like having an interface, however this late into "production" this may break many projects extending this class. Its not a major break and doesnt give much headache, but it is one nonetheless.

For this reason I would maybe use it in a 4.x branch.

**Comment by serbanghita** [comment]
@pquerner I don't see the practical reason for an interface unless you want to swap implementation or something like that.

I'm not sure if this project will live to see 4.x if Google succeeds with the [user-agent reduction initiative](https://developer.chrome.com/en/docs/privacy-sandbox/user-agent/) 🗡️

**Comment by serbanghita** [comment]
I believe https://github.com/serbanghita/Mobile-Detect/pull/936 is enough for extensibility

**Pull request closed without merging**
