### PR TITLE
fixed a bug in foreach

### PR DESCRIPTION
**Pull request by hainuo**
fixed a bug in foreach which will stop in the first iterator

### CODE REVIEW

**Comment by hainuo** [comment]
@serbanghita   well，i'll have a try.

**Comment by hainuo** [comment]
I add a new test function ,but i haven’t used testmodule,so i do not know
the result of the code

**Comment by serbanghita** [comment]
Tests are failing

```
$ php phpunit.phar -c tests/phpunit.xml
 PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from F:\webserver\www\git\test\Mobile-Detect-2.x\tests\phpunit.xml

..F

Time: 259 ms, Memory: 10.75Mb

There was 1 failure:

1) BasicTest::testCheckHttpHeadersForMobile
Failed asserting that actual size 13 matches expected size 12.

F:\webserver\www\git\test\Mobile-Detect-2.x\tests\BasicsTest.php:92

FAILURES!
Tests: 3, Assertions: 15, Failures: 1.

Serban@PC-SASA /F/webserver/www/git/test/Mobile-Detect-2.x (devel)
$ php phpunit.phar -c tests/phpunit.xml
 PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from F:\webserver\www\git\test\Mobile-Detect-2.x\tests\phpunit.xml

.....................F

Time: 319 ms, Memory: 10.75Mb

There was 1 failure:

1) BasicTest::testQuickHeaders with data set #4 (array('hello'))
Failed asserting that false is true.

F:\webserver\www\git\test\Mobile-Detect-2.x\tests\BasicsTest.php:373

FAILURES!
Tests: 22, Assertions: 83, Failures: 1.
```

**Comment by hainuo** [comment]
if headers like this 
```
    public function testCheckHttpHeadersForMobile()
    {
        $this->assertNotEmpty( $this->detect->getScriptVersion() );

        $this->detect->setHttpHeaders(array(
                'SERVER_SOFTWARE'       => 'Apache/2.2.15 (Linux) Whatever/4.0 PHP/5.2.13',
                'REQUEST_METHOD'        => 'POST',
                'HTTP_HOST'             => 'home.ghita.org',
                'HTTP_X_REAL_IP'        => '1.2.3.4',
                'HTTP_X_FORWARDED_FOR'  => '1.2.3.5',
                'HTTP_CONNECTION'       => 'close',
                'HTTP_USER_AGENT'       => 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A523 Safari/8536.25',
                'HTTP_ACCEPT'           => '',
                'HTTP_ACCEPT_LANGUAGE'  => 'en-us,en;q=0.5',
                'HTTP_ACCEPT_ENCODING'  => 'gzip, deflate',
                'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest',
                'HTTP_REFERER'          => 'http://mobiledetect.net',
                'HTTP_PRAGMA'           => 'no-cache',
                'HTTP_CACHE_CONTROL'    => 'no-cache',
                'REMOTE_ADDR'           => '11.22.33.44',
                'REQUEST_TIME'          => '01-10-2012 07:57',
                'HTTP_UA_CPU'           => 'ARM'  //this is the mobileHeaders's last key, when line 161 run true, it runs good
            ));

        //12 because only 13 start with HTTP_
        $this->assertCount( 13, $this->detect->getHttpHeaders() );
        $this->assertTrue( $this->detect->checkHttpHeadersForMobile() );
    }
```

then the function checkHttpHeadersForMobile  will just check about `HTTP_ACCEPT`,without checking about `HTTP_UA_CPU` which is written into the variable  `protected static $mobileHeaders` in line 161.

 
image

**Pull request merged**
