### PR TITLE
Add tablet devices

### PR DESCRIPTION
**Pull request by rahatlukumich**
In phones:
- Add "\\WiPhone\\W|\\WiPod\\W" to iPhone
- Add "Nokia":"\\WRM-\\d+.*Microsoft Windows|Lumia.*Microsoft Windows"

In mobile_os:
- Add "\\sWP7|Lumia.*Microsoft Windows|\\WRM-\\d+.*Microsoft Windows" to WindowsPhoneOS

In generic phones:
- add 'Explay[ _-]*(?:A350|HD|Advance|Indigo|Atom|Star|Sky|Fresh|X-tremer|Alto|Communicator)' (Explay)

In tablets:
- change "HTC_Flyer_P512|HTC Flyer|HTC Jetstream|HTC-P715a" to "HTC[ _\-](?:Flyer|P715a|Jetstream)" (match HTC Flyer P510)
- add 'Sprint (ATP.*) Build' to HTC
- add CnM tablets by regexp "CnM[ \-](?:Touchpad|TP)"
- in HP change "HP 8" to "HP [78].* Build"
- in HP change HP Slate (7|8|10) to HP Slate (6|7|8|10)
- in Archos change "\\bARCHOS (70|79|80|90|97|101|FAMILYPAD|)(b|)(G10| Cobalt| TITANIUM(HD|)| Xenon| Neon|XSK| 2| XS 2| PLATINUM| CARBON|GAMEPAD)\\b" to "Archos ([789]|10)[0-9]?[a-z]* ?(?:G9|G10|Helium|Titanium(HD|)|Cobalt|Platinum|Xenon|Carbon|Neon|XSK|2|XS 2|IT|GAMEPAD)[^/;]*"
- add "A1-830|A1-81[01]|A3-A[12][01]|B1-7[1235][01]|B1-810|B1-A71" to Acer
- add 'Numy' to AinolTablet
- Arnova's changed to 'arnova|ARCHM901|AN7CG2|AN7G2(DTE|I)?|AN7[BCDFH]?G3|A80KSC|AN8G2|AN8[BC]?G3|AN9G2I?|AN9G3|A101[BC]|AN10G2|AN10BG2(DT|I)?|AN10BG3(DT)?|AN10[CD]G3' 
- in bq add 'Aquaris|bq [^/;]+ Build'
- change CubeTablet regex to 'Cube|(U[0-9]+GT(?:[0-9]|[\\-_][a-z]+)|K8GT)'
- change to 'Dslide ?([^;/]+) Build' in Danew
- change to 'E-Boda ((?:Revo|Izzycomm|Essential|Impresspeed|Intelligence|Supreme)[^/;]+) Build' in Eboda
- add TA10CA3 to ECS
- change 'Venue 11|Venue 8|Venue 7|Dell Streak 10|Dell Streak 7' to  '(?:Dell )?(Streak|Venue) ?[^/;_ ]*(?:7|8|10|11)' in Dell
- change 'eZee[_']?(Tab|Go)[0-9]+|TabLC7|Looney Tunes Tab' to 'eZee[^a-z]*(Tab|Go)?([^;/]*) Build|STOREX LinkBox|TabLC7|Looney Tunes Tab' in Storex
- add 'SO-05F|SGP(?:6[24]1)[);/ ]' to Sony
- change '\\bK00F\\b|\\bK00C\\b|\\bK00E\\b|\\bK00L\\b' to ' K01[3A][);/ ]|K01E[);/ ]|K00U|(?:K011|K00L)[);/ ]|K014[);/ ]|K00F[);/ ]|K00C[);/ ]|K018[);/ ]' in Asus
- add 'Yoga Tablet([^;\/]+) Build' and B600|B10000 to Lenovo tablet
- change 'Nexus 4|Nexus 5|Nexus 6' to 'Nexus (?:4|5|6|7|9|10)' in Nexus
- add Primo ?(?:91|76) to MSI tablet
- add 'ONDA MID' to Onda
- add qualcore 1020 to overmax
- add '(?:SAMSUNG-)?(GT-(P|N8|N5)[0-9]+[a-z]?)|(?:SAMSUNG-)?((?:SM-[TNP]|GT-P)[a-z0-9_\\-]+)' to samsung
- add PMP5785C to Prestigio
- change 'Qilive 97R' to 'Qilive ([6-9][^;/]*)/' in Archos
- add 'KFARWI|Amazon (?:Tate|Jem)|Silk/\d+\.\d+' and make Android optional in kindle.
- change all ViewPad regexp in ViewSonic
- change to 'Smart ?Tab ?(?:III? ?)?(?:|4G|7|10|1)[);/ -]' in Vodafone
- change to 'miTab[ \-_]?([^/]+) Build' in Wolder
- change 'Xenta[ \-]Tab|Luna TAB|TAB09-410|TAB10-410|TAB07-485|TAB0[78]-200|TAB08-201-3G|TAB9-200|TAB09-211|TAB10-2[01]1|TAB13-201' in Yarvik
- add 'AT1S0|AT703|AT400|AT330|AT503' in Toshiba
- add 'Flylife[ _\-]?([^/;]+) Build' to Fly
- add 'Neon([79])[);/ ]|Sygnus[);/ ]|Deox[);/ ]' in iJoy
- add 'i-mobile i-note' to iMobile
- change '(MID(?:1024|1125|1126|1045|1048|1060|1065|4331|7010|7012|7014|7015A?|7016|7022|7032|7034|7035|7036|7042|7047|7048|7052|7065|7120|7127|8024|8042|8048|8065|8125|8127|8128|9042|9724|9740|9742))[);/ ]' in Coby
- change to 'Hudl ([^/;]+) Build' in Hudl
- add 'TouchPad\/(\\d+\\.\\d+)' to HP
- add 'Iconia Tab' to acer

In generic tablet:
- change BNTV250A to BN[TR]V[0-9]+ and add Nook (barnes & noble devices)
- add (Q7A\\+?)[);/ ] (Crius Mea tablet)
- add '(TA[CDQ]-[0-9]+)' (Denver tablet)
- add 'Andromax Tab 7.0|(Androtab[^/;]+) Build' (Smartfren)
- add Evertek '(E70[25]0HD|E805[01]HD|E9054HD|E8050HG|E7914HG)'
- add Gemini '(GEM[0-9]+[a-z]*)'
- add Gigaset 'Gigaset QV(1030|830)'
- add Vizio 'VTAB1008'
- add Grundig '(GR?-TB[0-9]+[a-z]*)'
- add Hisense 'M470BS[AE]|E2281|E270BSA'
- add Hi-Level 'HLV-T([a-z0-9]+)'
- add Hyundai 'Hyundai-HT'
- add 'iBall[ _]([^/;]*)[ _]Build' (iBall)
- add 'AUXUS (Core[^/;]+) Build' (iBerry)
- add 'Infinix (X[78]00)' (Infinix)
- add 'Le ?Pan|TC970 ([^;/]+)Build' (Le Pan)
- add 'Lenco ([^/;]*) Build' (Lenco)
- add '(MFC[0-9]{3}[a-z]{2,})' (Lexibook)
- add '(TAB950|TAB1062|E731|E812|E912|E1031)[);/ ]' (Logicom)
- add '(?:MPQC|MPDC)[0-9]+|(?:MID(?:7C|74C|82C|84C|801|811|701|711|170|77C|43C|102C|103C|104C|114C)|MP(?:843|717|718|1010|7007|7008|843|888|959|969)|MGP7)[);/ ]' (Mpman)
- add '(MID(?:06[SN]|08[S]?|12|13|14|15|701|702|703|704|705(?:DC)?|706[AS]?|707|708|709|711|712|714|717|781|801|802|1001|1002|1003|1004(?: 3G)?|1005|7802|9701|9702))[);/ ]' (Manta Multimedia)
- add 'SmartPad7503G|SmartPad970s2(?:3G)|M[_-]MP[0-9a-z]+|M-IPRO([18][01]0)[BW][);/ ]' (Mediacom)
- add 'SlidePad ?([^;/]*) Build' (Memup)
- add 'MyPad ([^;/]+) Build' (MyPhone)
- M.T.T.: 'M.T.T. ?Tablet([^;/]+)? Build'
- Oysters: 'Oysters (?!Arctic|Indian|Atlantic|Pacific)[^/;]+ Build'
- Point of View: 'POV_TAB|MOB-5045'
- Sencor: 'Sencor|ELEMENT[ _]?(?:7|8|9\.7|10[ _]1)(?:[ _]?V[23])?[);/ ]'
- Sumvision: '(Cyclone [^/;]+) Build'
- Thomson: '(?:Primo(7|8)|QM73[45]-8G|QM734-2|QM736-8G\(HD\)|MID1002)[);/ ]'
- Polaroid: 'Polaroid|(?:PMID|MIDC)[0-9a-z]+[);/ ]|MID(?:1014|0714)'
- PolyPad: 'POLY ?PAD'
- Ramos: 'Ramos ?([^/;]+) Build'
- Turbo-X: 'Turbo-X Ice[);/ ]|Turbo-X Tablet([^;/]+) Build'
- Sharp: 'SH-08E'
- Trevi: 'Trevi[ _]|TAB[ _]10[ _]3G[ _]V16|TAB[ _](7|8)[ _]3G[ _]V8|TAB9 3G|MINITAB 3GV|REVERSE[ _]5\.5[ _]?Q'
- Unowhy: 'QOOQ'
- Walton: 'Walpad ([^;/]+) Build'
- Wexler: '(?:Wexler[ _\-\.])?TAB[ _]10Q[);/ ]|Wexler[ _\-\.]([^;/]+) Build|Wexler[ _\-\.]([^);/]+)[);/]'
- Woxter: 'Woxter ([^/;]+) Build'
- Yuandao: 'N101[ _]DUAL(?:[ _]CORE)?(?:[ _]?2|\|\|)?(?:[ _]V11)?[);/ ]'
- add 'StarTab' (SFR)
- add 'RX-51 N900' (Nokia)
- add '(AC0731B|AC1024C|AC7803C|BC9710AM|EL72B|LC0720C|LC0723B|LC0725B|LC0804B|LC0808B|LC0809B|LC0810C|LC0816C|LC0901D|LC1016C|MT0724B|MT0729B|MT0729D|MT0811B|OC1020A|RC0709B|RC0710B|RC0718C|RC0719H|RC0721B|RC0722C|RC0726B|RC0734H|RC0743H|RC0817C|RC1018C|RC1019G|RC1025F|RC1301C|RC7802F|RC9711B|RC9712C|RC9716B|RC9717B|RC9724C|RC9726C|RC9727F|RC9730C|RC9731C|TS0807B|TS1013B|VM0711A|VM1017A|RC0813C|QS9719D|QS9718C|QS9715F|QS1023H|QS0815C|QS0730C|QS0728C|QS0717D|QS0716D|QS0715C|MT7801C)' (3q)
- add 'Explay[ _-]*(?:Informer|70[35])' (Explay)
- add 'Axxion ATAB-[0-9]+[);/ ]' (Axxion)

### CODE REVIEW

**Comment by h3nr1ke** [comment]
Show +1 ^^V

**Comment by serbanghita** [comment]
@rahatlukumich this looks interesting, but we generate `Mobile_Detect.json` from `Mobile_Detect.php` array of regexes. I'm afraid that if you don't commit these to `Mobile_Detect.php` I have to do it manually. Also I have to check that unit tests pass.

**Comment by rahatlukumich** [comment]
@serbanghita I haven't touched the php script. We have our own parser script in python and use only json for regexes. Is there any way I can help you to update this json? It's easier for us to keep one file in one place and do not touch it again after these additions.

**Comment by serbanghita** [comment]
@rahatlukumich hmm, I'll pick the `json` diffs and commit them to our main php file class `Mobile_Detect`.
Our workflow on the current `2.x` release is as follows:

1. Commit changes to regexes inside `Mobile_Detect.php`
1. Test the regex changes by running the unit tests
1. Generate json `Mobile_Detect.json` by running `export/exportToJSON.php`

As you can see each change in regexes must be validated by running our current tests.

If you cannot commit the above changes inside `Mobile_Detect.php`, I'll do them manually step by step.

**Comment by rahatlukumich** [comment]
@serbanghita Ok, great! Thank you. Further we can provide you with lots of new user agents (we have broad auditorium on avito.ru). We can approve some optimal for you workflow for this process.

**Comment by serbanghita** [comment]
Closing this since it cannot be merged, I am picking changes one by one in each request

**Pull request closed without merging**
