### PR TITLE
fix cache and generate short cache key

### PR DESCRIPTION
**Pull request by ilaoniu**
## Fix cache

The `$cacheItem` can only be `null` or boolean value, so `$cacheItem->get()` method call will throw an exception and be caught by the outer `try catch` code block, the cache will not work normally.

## Shorter cache key

When use database as cache driver, the cache key is too long(500 chars), with `md5` it can be limited to 50 chars.

## Cache TTL

When use Redis or Memcached as cache driver, the cache can automatically expire, otherwise the memory usage will continue to increase.

### CODE REVIEW

**Comment by serbanghita** [comment]
> The $cacheItem can only be null or boolean value

`$cacheItem` can only be  `CacheItem|null` because `$cacheKey` is always a base64 `string`.
I don't understand what do you mean.

> so $cacheItem->get() method call will throw an exception and be caught by the outer try catch code block, the cache will not work normally.

Indeed `get()` and `set()` can throw `Unhandled \Psr\SimpleCache\InvalidArgumentException`.
I think I need to handle and ignore the exception IF hypothetically the cache key is invalid.

> When use database as cache driver, the cache key is too long(500 chars), with md5 it can be limited to 50 chars.

this is a good point, I guess I made it base64 because I wanted the debug aspect of it. I'd make this configurable, def I'd not go for `md5` because of the collisions, but a `sha1`

> When use Redis or Memcached as cache driver, the cache can automatically expire, otherwise the memory usage will continue to increase.

Agree on the cache TTL, good catch!

**Comment by serbanghita** [comment]
What I can do is:

1. add TTL config
2. make the encoding of the cache key configurable (so I can keep backwards compat)
3. address `Unhandled \Psr\SimpleCache\InvalidArgumentException`. I guess nobody wants their detection script to break because of faulty cache

I'll fork your PR and make these changes

**Comment by serbanghita** [comment]
@ilaoniu tests are failing

**Comment by ilaoniu** [comment]
Oh, you are right. There is no problem with calling `$cacheItem->get()`.

**Comment by serbanghita** [comment]
@ilaoniu thank you!
I've merged it

I've added tests and made the config option `cacheKeyFn`, by default it's base64

**Pull request merged**
