### PR TITLE
Added missing samsung tablet SM-T585

### PR DESCRIPTION
**Pull request by leonrenkema**
We found that SM-T585 is also used

### CODE REVIEW

**Comment by ukko** [comment]
Hello, could you add to your PR another tablet from the Samsung **SM-T285**

UserAgent: Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-T285 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Safari/537.36"

**Comment by ukko** [comment]
@serbanghita 
Hi, can you merge this PR?

**Comment by serbanghita** [comment]
@ukko yes, I need to test it today. Thanks for providing the UA!

**Comment by ukko** [comment]
@serbanghita 

Hi! Now you can merge?

**Comment by gety9** [comment]
@serbanghita 

Serban hi,

There are 35 open PRs and they are not merged, could you explain why?
Is it because they fail when you test PRs on your end?

IMPORTANT: I am not criticizing or saying that you should merge them, i am just trying to understand how you determine what should be merged and what not.

Thank you!

**Comment by ukko** [comment]
plz plz plz

**Comment by serbanghita** [comment]
🙏  Sorry for the delay, I'm on it

**Comment by rozailan** [comment]
in fact I did not quite understand this system .. and I would like to ask
if this system can see whatsapp in other people's messages

**Comment by rozailan** [comment]
can you help me

**Comment by serbanghita** [comment]
@leonrenkema @ukko thank you for providing assistance for this issue 🍺 
@gety9 most of the PRs don't follow the [CONTRIBUTING](https://github.com/serbanghita/Mobile-Detect/blob/master/docs/CONTRIBUTING.md) guideline which make my job a lot harder to review them. If every PR would pass just like that, than this library wouldn't be so reliable. Also take into the account my own limitations as a person with personal life and job :) I'm working to improve my response time. Thanks for reminding me that!

**Comment by serbanghita** [comment]
Solved in `2.8.31`

**Pull request closed without merging**
